### PR TITLE
Adds support for the Drupal 10 version of CU Boulder Today (v2.0)

### PR DESCRIPTION
**Pull request by timurtripp**
This is a major update to the CU Boulder Campus News module. This update:

- [new] Adds support for the Drupal 10 version of CU Boulder Today by calling the JSON API. If the call to the JSON API fails, Campus News block features can still fall back to using the legacy (Drupal 7) API. Resolves CuBoulder/ucb_campus_news#12
- [bug, severity:minor] Fixes checkboxes not hiding underneath filters when "Filter by x" is unchecked. Resolves CuBoulder/ucb_campus_news#15

Technical information: This update contains an update hook.

### CODE REVIEW

**Comment by timurtripp** [comment]
At this point the work is mostly done and just needs some testing. I have the URL pointed at https://live-ucbprod-today.pantheonsite.io/ for testing purposes and will change over to https://www.colorado.edu/today when this pull request is marked as ready for review.

Tasks remaining:

- [ ] Figure out why the results back from JSON API doesn't seem to match the expected number. Will ask @patrickbrown-io.
- [ ] "Read more" page (can build on our existing work – will ask for help from @patrickbrown-io  or @jacob-korf and may create a sister issue).

**Comment by timurtripp** [comment]
Additional tasks remaining:

- [ ] Define taxonomy hierarchy requirements.
- [ ] Make Campus News block work with these requirements.

**Comment by timurtripp** [comment]
Two hierarchical taxonomy solutions possible:

- [x] 1: Parent check approach
  - Downside: Performance. `.parent` results in SQL JOINS on the backend and poor performance. 
  - **Completed and available for testing in the `issue/12-1` branch.**
- [ ] 2: All child approach
  - Downside: URL length. Supplying every child term id increases the URL length and may end up triggering a limit which we need to figure out for this and other JSON API applications.

**Comment by timurtripp** [comment]
Command necessary for testing on the prerelease Today site:

```sh
drush config:set ucb_campus_news.configuration baseURL 'https://live-ucbprod-today.pantheonsite.io'
```

Reset back to default with:

```sh
drush config:set ucb_campus_news.configuration baseURL 'https://www.colorado.edu/today'
```

**Review by jcsparks — COMMENTED** [review]
Works well

**Pull request merged**
